version: '3.8'

# Note: Prometheus doesn't support variable substitution aside from labels.. 
# so the config need to have variables updated manually, or use SED or similar to replace them from here

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}
  prometheus_config:

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - prometheus_config:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - monitoring
    depends_on:
      - config-writer

  config-writer:
    image: quay.io/curl/curl-base:latest
    command: 
      - "curl -L -o /config/prometheus.yml https://raw.githubusercontent.com/alex-harper/config/main/prometheus.yml"
    volumes:
      - prometheus_config:/config
